config/routes.rb
Rails.application.routes.draw do
  get 'guida_analisi_tecnica/index'

  get 'guida_analisi_tecnica/leFasiDelMercato'

  get 'guida_analisi_tecnica/ilTrend'

  get 'guida_analisi_tecnica/laTrendline'

  get 'guida_analisi_tecnica/inversioneDiTrend'

  get 'guida_analisi_tecnica/figureGrafiche'

  get 'guida_analisi_tecnica/testaESpalla'

  get 'guida_analisi_tecnica/doppioTriploMinimoMassimo'

  get 'guida_analisi_tecnica/spike'

  get 'guida_analisi_tecnica/triangoliFlagPennantRettangoli'

  get 'guida_analisi_tecnica/candeleGiapponesi'

  get 'guida_analisi_tecnica/standardELong'

  get 'guida_analisi_tecnica/marubozu'

  get 'guida_analisi_tecnica/harami'

  get 'guida_analisi_tecnica/doji'

  get 'guida_analisi_tecnica/configurazioniCandlestick'

  get 'guida_analisi_tecnica/bullishBearishEngulfing'

  get 'guida_analisi_tecnica/morningEveningStar'

  get 'guida_analisi_tecnica/hammerShootingStar'

  get 'guida_analisi_tecnica/hangingMan'

  get 'guida_analisi_tecnica/gap'

  get 'guida_analisi_tecnica/oscillatori'

  get 'guida_analisi_tecnica/rsi'

  get 'guida_analisi_tecnica/macd'

  get 'guida_analisi_tecnica/stocastico'

  get 'guida_analisi_tecnica/bandeDiBollinger'
  #get 'xyz' => 'guida_analisi_tecnica#bandeDiBollinger'

  get 'guida_analisi_tecnica/indicatori'

  get 'guida_analisi_tecnica/medieMobili'

  get 'guida_analisi_tecnica/volumi'

  get 'guida_analisi_tecnica/ondeDiElliot'

  get 'guida_analisi_tecnica/ritracciamentiDiFibonacci'

  mount Ckeditor::Engine => '/ckeditor'
  get 'chi_siamo/index'
  get 'chi_siamo/' => 'chi_siamo#index'

  get 'contatti/index'
  get 'contatti/' => 'contatti#index'

  get 'sources/source1'

  get 'sources/source2'

  get 'sources/source3'

  get 'sources/source4'

  get 'sources/source5'

  get 'sources/source6'

  get 'trading_plan/index'

  get 'filters/filter_overAllResistancesStocks'
  get 'filters/filter_belowAllSupportsStocks'
  
  get 'filters/filter_overResistanceBorsaItaliana'
  get 'filters/filter_belowSupportBorsaItaliana'
  
  get 'filters/filter_overResistanceSoleXXIVOre'
  get 'filters/filter_belowSupportSoleXXIVOre'
  
  get 'filters/filter_overResistanceRepubblica'
  get 'filters/filter_belowSupportRepubblica'

  get 'filters/filter_suggestionsSoleXXIVOre'
  get 'filters/filter_suggestionsInvestingDotCom'
  get 'filters/filter_suggestionsMilanoFinanza'

  get 'filters/filter_overResistanceStocksOnStudy'
  get 'filters/filter_belowSupportStocksOnStudy'

  
  get 'filters/filter_trendReinforcement'
  get 'filters/filter_trendChanging'
  
  
  get 'study_page/index'
  get 'study_page/' => 'study_page#index'
  post 'study_page/index'  => 'study_page#create' 

  get 'stock_page/index'
  get 'stock_page/' => 'stock_page#index'
  

  resources :markets
  resources :studies
  resources :analyses
  resources :stocks
  resources :urls
  
  get 'welcome/index'
  get 'welcome/' => 'welcome#index'

  root 'welcome#index'

  get 'signup'  => 'users#new' 
  resources :users

  get 'login'  => 'sessions#new' 

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
  
  Rails.application.routes.draw do
  get 'guida_analisi_tecnica/index'

  get 'guida_analisi_tecnica/leFasiDelMercato'

  get 'guida_analisi_tecnica/ilTrend'

  get 'guida_analisi_tecnica/laTrendline'

  get 'guida_analisi_tecnica/inversioneDiTrend'

  get 'guida_analisi_tecnica/figureGrafiche'

  get 'guida_analisi_tecnica/testaESpalla'

  get 'guida_analisi_tecnica/doppioTriploMinimoMassimo'

  get 'guida_analisi_tecnica/spike'

  get 'guida_analisi_tecnica/triangoliFlagPennantRettangoli'

  get 'guida_analisi_tecnica/candeleGiapponesi'

  get 'guida_analisi_tecnica/standardELong'

  get 'guida_analisi_tecnica/marubozu'

  get 'guida_analisi_tecnica/harami'

  get 'guida_analisi_tecnica/doji'

  get 'guida_analisi_tecnica/configurazioniCandlestick'

  get 'guida_analisi_tecnica/bullishBearishEngulfing'

  get 'guida_analisi_tecnica/morningEveningStar'

  get 'guida_analisi_tecnica/hammerShootingStar'

  get 'guida_analisi_tecnica/hangingMan'

  get 'guida_analisi_tecnica/gap'

  get 'guida_analisi_tecnica/oscillatori'

  get 'guida_analisi_tecnica/rsi'

  get 'guida_analisi_tecnica/macd'

  get 'guida_analisi_tecnica/stocastico'

  get 'guida_analisi_tecnica/bandeDiBollinger'

  get 'guida_analisi_tecnica/indicatori'

  get 'guida_analisi_tecnica/medieMobili'

  get 'guida_analisi_tecnica/volumi'

  get 'guida_analisi_tecnica/ondeDiElliot'

  get 'guida_analisi_tecnica/ritracciamentiDiFibonacci'

    #mount Ckeditor::Engine => '/ckeditor'
    #root to: "posts#index"
  
    resources :posts
  end
  
  
  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'
   
  
  #FTSE MIB
  get 'analisi_tecnica_titolo/' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/index' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/a2a'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/atlantia'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/azimut_holding'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_generali'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_mediolanum'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banco_bpm'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/bper_banca'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/brembo'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/buzzi_unicem'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/campari'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/cnh_industrial'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/enel'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/eni'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/exor'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ferrari'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/fiat_chrysler_automobiles'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/finecobank'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/generali'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/intesa_sanpaolo'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/italgas'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/leonardo'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/luxottica'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/mediaset'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/mediobanca'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/moncler'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/poste_italiane'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/prysmian'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/recordati'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/saipem'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/salvatore_ferragamo'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/snam'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/stmicroelectronics'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/telecom_italia'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/tenaris'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/terna_rete_elettrica_nazionale'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ubi_banca'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/unicredit'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/unipol'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/unipolsai'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/yoox_net_a_porter_group'  => 'analisi_tecnica_titolo#index'
  
  
  #A
  get 'analisi_tecnica_titolo/acea'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/acotel_group'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/acsm_agam'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/aedes'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/aeffe'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/aeroporto_guglielmo_marconi'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/alerion_cleanpower'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ambienthesis'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/amplifon'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/anima_holding'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ansaldo_sts'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ascopiave'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/astaldi'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/astm'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/autogrill'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/autostrade_meridionali'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/avio'  => 'analisi_tecnica_titolo#index'
  
  
  #B
  get 'analisi_tecnica_titolo/bec_speakers' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_carige' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_farmafactoring' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_finnat' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_ifis' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_intermobiliare' => 'analisi_tecnica_titolo#index'

app/models/url.rb
class Url < ApplicationRecord
  validates :isin, presence: true, uniqueness: true
  validates :url1, presence: true
  validates :url2, :url3, :url4, :url5, :url6, :url7, :url8, :url9, :url10, uniqueness: true, allow_blank: true
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]
  before_action :require_user

  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.all
    @user = User.find_by_email($user_email) 
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: 'Url was successfully created.' }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url, notice: 'Url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:isin, :url1, :url2, :url3, :url4, :url5, :url6, :url7, :url8, :url9, :url10)
    end
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/urls/_form.html.erb
<%= form_for(url) do |f| %>
  <% if url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :isin %>
    <%= f.text_field :isin %>
  </div>

  <div class="field">
    <%= f.label :url1 %>
    <%= f.text_field :url1 %>
  </div>

  <div class="field">
    <%= f.label :url2 %>
    <%= f.text_field :url2 %>
  </div>

  <div class="field">
    <%= f.label :url3 %>
    <%= f.text_field :url3 %>
  </div>

  <div class="field">
    <%= f.label :url4 %>
    <%= f.text_field :url4 %>
  </div>

  <div class="field">
    <%= f.label :url5 %>
    <%= f.text_field :url5 %>
  </div>

  <div class="field">
    <%= f.label :url6 %>
    <%= f.text_field :url6 %>
  </div>

  <div class="field">
    <%= f.label :url7 %>
    <%= f.text_field :url7 %>
  </div>

  <div class="field">
    <%= f.label :url8 %>
    <%= f.text_field :url8 %>
  </div>

  <div class="field">
    <%= f.label :url9 %>
    <%= f.text_field :url9 %>
  </div>

  <div class="field">
    <%= f.label :url10 %>
    <%= f.text_field :url10 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/urls/edit.html.erb
<main id="main">
    <div id="content" class="container">
        <div class="row">
            <section id="primary" class="col-sm-12">
                <h1>Editing Url</h1>
                <%= render 'form', url: @url %>
                <%= link_to 'Show', @url %> |<%= link_to 'Back', urls_path %>
            </section>
        </div>
    </div>
</main>

app/views/urls/index.html.erb
<% meta_tag :robots, 'noindex, nofollow' %>


<main id="main">
    <div id="content" class="container">
        <div class="row">
            <div id="primary" class="col-sm-12">
                <p id="notice">
                    <%= notice %>
                </p>
                <h1>Urls</h1>
                <table class="tablesorter">
                    <thead>
                        <tr>
                            <th>
                                Isin
                            </th>
                            <th>
                                Url 1
                            </th>
                            <th>
                                Url 2
                            </th>
                            <th>
                                Url 3
                            </th>
                            <th>
                                Url 4
                            </th>
                            <th>
                                Url 5
                            </th>
                            <th>
                                Url 6
                            </th>
                            <th>
                                Url 7
                            </th>
                            <th>
                                Url 8
                            </th>
                            <th>
                                Url 9
                            </th>
                            <th>
                                Url 10
                            </th>
                            <th colspan="3">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @urls.each do |url| %>
                        <tr class="<%= cycle('even', 'odd') -%>">
                            <td>
                                <%= url.isin %>
                            </td>
                            <td title="<%= url.url1 %>">
                                <%= url.url1 %>
                            </td>
                            <td title="<%= url.url2 %>">
                                <%= url.url2 %>
                            </td>
                            <td title="<%= url.url3 %>">
                                <%= url.url3 %>
                            </td>
                            <td title="<%= url.url4 %>">
                                <%= url.url4 %>
                            </td>
                            <td title="<%= url.url5 %>">
                                <%= url.url5 %>
                            </td>
                            <td title="<%= url.url6 %>">
                                <%= url.url6 %>
                            </td>
                            <td title="<%= url.url7 %>">
                                <%= url.url7 %>
                            </td>
                            <td title="<%= url.url8 %>">
                                <%= url.url8 %>
                            </td>
                            <td title="<%= url.url9 %>">
                                <%= url.url9 %>
                            </td>
                            <td title="<%= url.url10 %>">
                                <%= url.url10 %>
                            </td>
                            <td>
                                <%= link_to 'Show', url %>
                            </td>
                            <td>
                                <%= link_to 'Edit', edit_url_path(url) %>
                            </td>
                            <td>
                                <%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
                <br>
                <%= link_to 'New Url', new_url_path %>
            </div>
        </div>
    </div>
</main>

app/views/urls/new.html.erb
<h1>New Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<main id="main">
    <div id="content" class="container">
        <div class="row">
            <section id="primary" class="col-sm-12">
                <p id="notice">
                    <%= notice %>
                </p>
                <p>
                    <strong>Isin:</strong>
                    <%= @url.isin %>
                </p>
                <p>
                    <strong>Url1:</strong>
                    <%= @url.url1 %>
                </p>
                <p>
                    <strong>Url2:</strong>
                    <%= @url.url2 %>
                </p>
                <p>
                    <strong>Url3:</strong>
                    <%= @url.url3 %>
                </p>
                <p>
                    <strong>Url4:</strong>
                    <%= @url.url4 %>
                </p>
                <p>
                    <strong>Url5:</strong>
                    <%= @url.url5 %>
                </p>
                <p>
                    <strong>Url6:</strong>
                    <%= @url.url6 %>
                </p>
                <p>
                    <strong>Url7:</strong>
                    <%= @url.url7 %>
                </p>
                <p>
                    <strong>Url8:</strong>
                    <%= @url.url8 %>
                </p>
                <p>
                    <strong>Url9:</strong>
                    <%= @url.url9 %>
                </p>
                <p>
                    <strong>Url10:</strong>
                    <%= @url.url10 %>
                </p>
                <%= link_to 'Edit', edit_url_path(@url) %> |<%= link_to 'Back', urls_path %>
            </section>
        </div>
    </div>
</main>