config/routes.rb
Rails.application.routes.draw do
  get 'guida_analisi_tecnica/index'

  get 'guida_analisi_tecnica/leFasiDelMercato'

  get 'guida_analisi_tecnica/ilTrend'

  get 'guida_analisi_tecnica/laTrendline'

  get 'guida_analisi_tecnica/inversioneDiTrend'

  get 'guida_analisi_tecnica/figureGrafiche'

  get 'guida_analisi_tecnica/testaESpalla'

  get 'guida_analisi_tecnica/doppioTriploMinimoMassimo'

  get 'guida_analisi_tecnica/spike'

  get 'guida_analisi_tecnica/triangoliFlagPennantRettangoli'

  get 'guida_analisi_tecnica/candeleGiapponesi'

  get 'guida_analisi_tecnica/standardELong'

  get 'guida_analisi_tecnica/marubozu'

  get 'guida_analisi_tecnica/harami'

  get 'guida_analisi_tecnica/doji'

  get 'guida_analisi_tecnica/configurazioniCandlestick'

  get 'guida_analisi_tecnica/bullishBearishEngulfing'

  get 'guida_analisi_tecnica/morningEveningStar'

  get 'guida_analisi_tecnica/hammerShootingStar'

  get 'guida_analisi_tecnica/hangingMan'

  get 'guida_analisi_tecnica/gap'

  get 'guida_analisi_tecnica/oscillatori'

  get 'guida_analisi_tecnica/rsi'

  get 'guida_analisi_tecnica/macd'

  get 'guida_analisi_tecnica/stocastico'

  get 'guida_analisi_tecnica/bandeDiBollinger'
  #get 'xyz' => 'guida_analisi_tecnica#bandeDiBollinger'

  get 'guida_analisi_tecnica/indicatori'

  get 'guida_analisi_tecnica/medieMobili'

  get 'guida_analisi_tecnica/volumi'

  get 'guida_analisi_tecnica/ondeDiElliot'

  get 'guida_analisi_tecnica/ritracciamentiDiFibonacci'

  mount Ckeditor::Engine => '/ckeditor'
  get 'chi_siamo/index'
  get 'chi_siamo/' => 'chi_siamo#index'

  get 'contatti/index'
  get 'contatti/' => 'contatti#index'

  get 'sources/source1'

  get 'sources/source2'

  get 'sources/source3'

  get 'sources/source4'

  get 'sources/source5'

  get 'sources/source6'

  get 'trading_plan/index'

  get 'filters/filter_overAllResistancesStocks'
  get 'filters/filter_belowAllSupportsStocks'
  
  get 'filters/filter_overResistanceBorsaItaliana'
  get 'filters/filter_belowSupportBorsaItaliana'
  
  get 'filters/filter_overResistanceSoleXXIVOre'
  get 'filters/filter_belowSupportSoleXXIVOre'
  
  get 'filters/filter_overResistanceRepubblica'
  get 'filters/filter_belowSupportRepubblica'

  get 'filters/filter_suggestionsSoleXXIVOre'
  get 'filters/filter_suggestionsInvestingDotCom'
  get 'filters/filter_suggestionsMilanoFinanza'

  get 'filters/filter_overResistanceStocksOnStudy'
  get 'filters/filter_belowSupportStocksOnStudy'

  
  get 'filters/filter_trendReinforcement'
  get 'filters/filter_trendChanging'
  
  
  get 'study_page/index'
  get 'study_page/' => 'study_page#index'
  post 'study_page/index'  => 'study_page#create' 

  get 'stock_page/index'
  get 'stock_page/' => 'stock_page#index'
  

  resources :markets
  resources :studies
  resources :analyses
  resources :stocks
  resources :urls
  
  get 'welcome/index'
  get 'welcome/' => 'welcome#index'

  root 'welcome#index'

  get 'signup'  => 'users#new' 
  resources :users

  get 'login'  => 'sessions#new' 

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
  
  Rails.application.routes.draw do
  get 'guida_analisi_tecnica/index'

  get 'guida_analisi_tecnica/leFasiDelMercato'

  get 'guida_analisi_tecnica/ilTrend'

  get 'guida_analisi_tecnica/laTrendline'

  get 'guida_analisi_tecnica/inversioneDiTrend'

  get 'guida_analisi_tecnica/figureGrafiche'

  get 'guida_analisi_tecnica/testaESpalla'

  get 'guida_analisi_tecnica/doppioTriploMinimoMassimo'

  get 'guida_analisi_tecnica/spike'

  get 'guida_analisi_tecnica/triangoliFlagPennantRettangoli'

  get 'guida_analisi_tecnica/candeleGiapponesi'

  get 'guida_analisi_tecnica/standardELong'

  get 'guida_analisi_tecnica/marubozu'

  get 'guida_analisi_tecnica/harami'

  get 'guida_analisi_tecnica/doji'

  get 'guida_analisi_tecnica/configurazioniCandlestick'

  get 'guida_analisi_tecnica/bullishBearishEngulfing'

  get 'guida_analisi_tecnica/morningEveningStar'

  get 'guida_analisi_tecnica/hammerShootingStar'

  get 'guida_analisi_tecnica/hangingMan'

  get 'guida_analisi_tecnica/gap'

  get 'guida_analisi_tecnica/oscillatori'

  get 'guida_analisi_tecnica/rsi'

  get 'guida_analisi_tecnica/macd'

  get 'guida_analisi_tecnica/stocastico'

  get 'guida_analisi_tecnica/bandeDiBollinger'

  get 'guida_analisi_tecnica/indicatori'

  get 'guida_analisi_tecnica/medieMobili'

  get 'guida_analisi_tecnica/volumi'

  get 'guida_analisi_tecnica/ondeDiElliot'

  get 'guida_analisi_tecnica/ritracciamentiDiFibonacci'

    #mount Ckeditor::Engine => '/ckeditor'
    #root to: "posts#index"
  
    resources :posts
  end
  
  
  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'
   
  
  #FTSE MIB
  get 'analisi_tecnica_titolo/' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/index' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/a2a'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/atlantia'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/azimut_holding'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_generali'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_mediolanum'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banco_bpm'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/bper_banca'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/brembo'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/buzzi_unicem'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/campari'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/cnh_industrial'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/enel'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/eni'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/exor'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ferrari'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/fiat_chrysler_automobiles'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/finecobank'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/generali'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/intesa_sanpaolo'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/italgas'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/leonardo'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/luxottica'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/mediaset'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/mediobanca'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/moncler'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/poste_italiane'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/prysmian'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/recordati'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/saipem'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/salvatore_ferragamo'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/snam'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/stmicroelectronics'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/telecom_italia'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/tenaris'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/terna_rete_elettrica_nazionale'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ubi_banca'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/unicredit'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/unipol'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/unipolsai'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/yoox_net_a_porter_group'  => 'analisi_tecnica_titolo#index'
  
  
  #A
  get 'analisi_tecnica_titolo/acea'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/acotel_group'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/acsm_agam'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/aedes'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/aeffe'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/aeroporto_guglielmo_marconi'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/alerion_cleanpower'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ambienthesis'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/amplifon'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/anima_holding'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ansaldo_sts'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ascopiave'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/astaldi'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/astm'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/autogrill'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/autostrade_meridionali'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/avio'  => 'analisi_tecnica_titolo#index'
  
  
  #B
  get 'analisi_tecnica_titolo/bec_speakers' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_carige' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_farmafactoring' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_finnat' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_ifis' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_intermobiliare' => 'analisi_tecnica_titolo#index'

app/views/shared/_footer.erb
<footer id="footer-area">
    <div class="container">
        <div class="footer-widget-area">
        	
            <div class="col-sm-6 col-md-4 footer-widget">
                <div id="nav_menu-2" class="widget widget_nav_menu">
                    <h3 class="widgettitle">Altri link</h3>
                    <div class="menu-short-container">
                        <ul id="menu-short" class="menu">
                            <li class="menu-item">
								<%= link_to 'Cos\'è Trading Radar', chi_siamo_index_path, title: 'Cos\'è Trading Radar' %>
                            </li>
                            <li class="menu-item">
                                <%= link_to 'Contatti', contact_path, title: 'Pagina contatti' %>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
			
            <div class="col-sm-6 col-md-4 footer-widget">
                <div id="text-3" class="widget widget_text">
                    <div class="textwidget">
                        <p>
                            <%= image_tag 'trading-radar-logo-small-alpha.png', alt: $appName + ' logo' %>
                        </p>
                        <h3>
                        	<%= $appName %>
							<small>Ver. <%= $appVersion%></small>
                        </h3>
						
                        <p>
                            <%= $appDescription %>
                        </p>
                        <p>
                            Per commenti e suggerimento <strong><%=mail_to "marco@tradingradar.net", "contatta"%></strong> l&apos;amministratore del sito.
                        </p>
                    </div>
                </div>
            </div>
			
            <div class="col-sm-12 col-md-4 footer-widget">
                <div class="site-info">
                    <div class="copyright">
                        Template base on <a href="https://colorlib.com/dazzling/" title="Dazzling Demo">Dazzling Demo</a>
                        Theme by <a href="https://colorlib.com/wp/" target="_blank">Colorlib</a>
                        <div>
                            Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a>
                            from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>
                            is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>
                        </div>
                        <div>
                            Icons made by <a href="https://www.flaticon.com/authors/pixel-perfect" title="Pixel perfect">Pixel perfect</a>
                            from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>
                            is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>
                        </div>
                    </div>
                </div>
            </div>
			
        </div>
    </div>
    <div class="scroll-to-top">
        <i class="fa fa-angle-up"></i>
    </div>
</footer>

app/views/shared/_last_study.html.erb
	<% if @lastStudy %>
	<table class="tablesorter nojs">
	    <thead>
	        <tr>
	            <th>
	                Resistenza
	            </th>
	            <th>
	                Supporto
	            </th>
	            <th>
	                Direzione
	            </th>
	            <th>
	                Media ponderata 1
	            </th>
	            <th>
	                Media ponderata 2
	            </th>
	            <th>
	                Gap
	            </th>
	            <th>
	                Posizione (Long/Short)
	            </th>
	        </tr>
	    </thead>
	    <tbody>
	        <tr>
	            <td>
	                <%= @lastStudy.resistance %>
	            </td>
	            <td>
	                <%= @lastStudy.support %>
	            </td>
	            <td>
	                <%= @lastStudy.direction %>
	            </td>
	            <td>
	                <%= @lastStudy.mmp1 %>
	            </td>
	            <td>
	                <%= @lastStudy.mmp2 %>
	            </td>
	            <td>
	                <%= @lastStudy.gap %>
	            </td>
	            <td>
	                <%= @lastStudy.trading_position %>
	            </td>
	        </tr>
	    </tbody>
	</table>
	<table class="tablesorter nojs">
	    <thead>
	        <tr>
	            <th>
	                Reversal Chart Pattern
	            </th>
	            <th>
	                Continuation Chart Pattern
	            </th>
	            <th>
	                Reversal Candlestick
	            </th>
	            <th>
	                Continuation Candlestick
	            </th>
	        </tr>
	    </thead>
	    <tbody>
	        <tr>
	            <td>
	                <%= @lastStudy.reversal_chart_pattern %>
	            </td>
	            <td>
	                <%= @lastStudy.continuation_chart_pattern %>
	            </td>
	            <td>
	                <%= @lastStudy.reversal_candlestick %>
	            </td>
	            <td>
	                <%= @lastStudy.continuation_candlestick %>
	            </td>
	        </tr>
	    </tbody>
	</table>
	<table class="tablesorter nojs">
	    <thead>
	        <tr>
	            <th>
	                RSI
	            </th>
	            <th>
	                RSI Cross
	            </th>
	            <th>
	                RSI Divergence
	            </th>
	            <th>
	                Stoch
	            </th>
	            <th>
	                Stoch Cross
	            </th>
	            <th>
	                Stoch Divergence
	            </th>
	            <th>
	                MACD
	            </th>
	            <th>
	                MACD Cross
	            </th>
	        </tr>
	    </thead>
	    <tbody>
	        <tr>
	            <td>
	                <%= @lastStudy.rsi %>
	            </td>
	            <td>
	                <%= @lastStudy.rsi_cross %>
	            </td>
	            <td>
	                <%= @lastStudy.rsi_divergence %>
	            </td>
	            <td>
	                <%= @lastStudy.stoch %>
	            </td>
	            <td>
	                <%= @lastStudy.stoch_cross %>
	            </td>
	            <td>
	                <%= @lastStudy.stoch_divergence %>
	            </td>
	            <td>
	                <%= @lastStudy.macd %>
	            </td>
	            <td>
	                <%= @lastStudy.macd_cross %>
	            </td>
	        </tr>
	    </tbody>
	</table>
	<table class="tablesorter nojs">
	    <thead>
	        <tr>
	            <th>
	                Buy
	            </th>
	            <th>
	                Sell
	            </th>
	            <th>
	                Stop Loss
	            </th>
	        </tr>
	    </thead>
	    <tbody>
	        <tr>
	            <td>
	                <%= @lastStudy.buy %>
	            </td>
	            <td>
	                <%= @lastStudy.sell %>
	            </td>
	            <td>
	                <%= @lastStudy.stop_loss %>
	            </td>
	        </tr>
	    </tbody>
	</table>
	<div>
	    Ulteriori note:
	    <div class="note">
	        <%= @lastStudy.note %>
	    </div>
	</div>
	<div>
	    Questo titolo ha <%= @studiesSize %> studio/i. 
	</div>
	<% end %>

app/views/shared/_namePriceVariation.erb
<header class="page-header">
    <h1 class="entry-title">
    	
    	
		<% if File.file?("#{Rails.public_path}/images/logos/" + @stock.cod + ".png") and @stock.cod %>
		  <%= image_tag("/images/logos/" + @stock.cod + ".png", class: "stock-logo") %>
		<% else %>
			<%= @stock.name %>
		<% end %>
			
		
    	
        <small>
        	<%= @stock.last_price %>&euro;&nbsp;/&nbsp;<span class="<%= colorClass(@stock.variation)%>"><%=@stock.variation %>%</span>
    	</small>
    </h1>
</header>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default">
    <div class="container">	
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div id="logo">
                <h1 class="site-title">
                	<a class="navbar-brand" href="/" title="<%= $appName %>" rel="home">
                		<%= image_tag 'trading-radar-logo-small-alpha.png', alt: $appName + ' logo', class: 'main-logo' %>
                		<%= $appName %>
					</a>
				</h1>
            </div>
            <p class="site-description">
                <%= $appDescription %>
            </p>
        </div>
	
        <div id="navbar" class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
                <li class="<%= 'active' if current_page?(controller: 'welcome', action: 'index') || current_page?(root_url) %>" >
                    <%= link_to 'Home', welcome_index_path, title: 'Home page' %>
                </li>
				<li class="<%= 'active' if current_page?(controller: 'posts', action: 'index') %>" >
                    <%= link_to 'Analisi titoli', posts_path, title: 'Analisi tecnica titoli' %>
                </li>
                <li class="<%= 'active' if current_page?(controller: 'chi_siamo', action: 'index') %>">
					<%= link_to 'Cos\'è Trading Radar', chi_siamo_index_path, title: 'Cos\'è Trading Radar' %>
                </li>                
				
				<% if $isAdmin %>
				<li>
					<a title="Database" href="#" data-toggle="dropdown" class="dropdown-toggle">Database <span class="caret"></span></a>
                    <ul role="menu" class=" dropdown-menu">                 				
						<li>
							<%= link_to urls_url do %>
							    <i class="fa fa-link"></i>&nbsp;Url
							<% end %>
						</li>
						<li>
							<%= link_to stocks_url do %>
							    <i class="fa fa-line-chart"></i>&nbsp;Stock
							<% end %>
						</li>
						<li>
							<%= link_to analyses_url do %>
							    <i class="fa fa-flask"></i>&nbsp;Analisi
							<% end %>
						</li>
						<li>
							<%= link_to studies_url do %>
							    <i class="fa fa-gears"></i>&nbsp;Studi
							<% end %>
						</li>
						<li>
							<%= link_to markets_url do %>
							    <i class="fa fa-pie-chart"></i>&nbsp;Mercati
							<% end %>
						</li>							
                    </ul>
                </li>
				<% end %>
										
				<li>
					<% if $user.present? %>
						<%= link_to logout_url, :method => :delete do %>
						    <i class="fa fa-sign-out"></i> Log out
						<% end %>					
					<%else%>		
						<%= link_to login_url do %>
						    <i class="fa fa-user"></i> Log in
						<% end %>
					<%end%>
                </li>

            </ul>
        </div>
	</div>
</nav>