config/routes.rb
Rails.application.routes.draw do
  get 'guida_analisi_tecnica/index'

  get 'guida_analisi_tecnica/leFasiDelMercato'

  get 'guida_analisi_tecnica/ilTrend'

  get 'guida_analisi_tecnica/laTrendline'

  get 'guida_analisi_tecnica/inversioneDiTrend'

  get 'guida_analisi_tecnica/figureGrafiche'

  get 'guida_analisi_tecnica/testaESpalla'

  get 'guida_analisi_tecnica/doppioTriploMinimoMassimo'

  get 'guida_analisi_tecnica/spike'

  get 'guida_analisi_tecnica/triangoliFlagPennantRettangoli'

  get 'guida_analisi_tecnica/candeleGiapponesi'

  get 'guida_analisi_tecnica/standardELong'

  get 'guida_analisi_tecnica/marubozu'

  get 'guida_analisi_tecnica/harami'

  get 'guida_analisi_tecnica/doji'

  get 'guida_analisi_tecnica/configurazioniCandlestick'

  get 'guida_analisi_tecnica/bullishBearishEngulfing'

  get 'guida_analisi_tecnica/morningEveningStar'

  get 'guida_analisi_tecnica/hammerShootingStar'

  get 'guida_analisi_tecnica/hangingMan'

  get 'guida_analisi_tecnica/gap'

  get 'guida_analisi_tecnica/oscillatori'

  get 'guida_analisi_tecnica/rsi'

  get 'guida_analisi_tecnica/macd'

  get 'guida_analisi_tecnica/stocastico'

  get 'guida_analisi_tecnica/bandeDiBollinger'
  #get 'xyz' => 'guida_analisi_tecnica#bandeDiBollinger'

  get 'guida_analisi_tecnica/indicatori'

  get 'guida_analisi_tecnica/medieMobili'

  get 'guida_analisi_tecnica/volumi'

  get 'guida_analisi_tecnica/ondeDiElliot'

  get 'guida_analisi_tecnica/ritracciamentiDiFibonacci'

  mount Ckeditor::Engine => '/ckeditor'
  get 'chi_siamo/index'
  get 'chi_siamo/' => 'chi_siamo#index'

  get 'contatti/index'
  get 'contatti/' => 'contatti#index'

  get 'sources/source1'

  get 'sources/source2'

  get 'sources/source3'

  get 'sources/source4'

  get 'sources/source5'

  get 'sources/source6'

  get 'trading_plan/index'

  get 'filters/filter_overAllResistancesStocks'
  get 'filters/filter_belowAllSupportsStocks'
  
  get 'filters/filter_overResistanceBorsaItaliana'
  get 'filters/filter_belowSupportBorsaItaliana'
  
  get 'filters/filter_overResistanceSoleXXIVOre'
  get 'filters/filter_belowSupportSoleXXIVOre'
  
  get 'filters/filter_overResistanceRepubblica'
  get 'filters/filter_belowSupportRepubblica'

  get 'filters/filter_suggestionsSoleXXIVOre'
  get 'filters/filter_suggestionsInvestingDotCom'
  get 'filters/filter_suggestionsMilanoFinanza'

  get 'filters/filter_overResistanceStocksOnStudy'
  get 'filters/filter_belowSupportStocksOnStudy'

  
  get 'filters/filter_trendReinforcement'
  get 'filters/filter_trendChanging'
  
  
  get 'study_page/index'
  get 'study_page/' => 'study_page#index'
  post 'study_page/index'  => 'study_page#create' 

  get 'stock_page/index'
  get 'stock_page/' => 'stock_page#index'
  

  resources :markets
  resources :studies
  resources :analyses
  resources :stocks
  resources :urls
  
  get 'welcome/index'
  get 'welcome/' => 'welcome#index'

  root 'welcome#index'

  get 'signup'  => 'users#new' 
  resources :users

  get 'login'  => 'sessions#new' 

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
  
  Rails.application.routes.draw do
  get 'guida_analisi_tecnica/index'

  get 'guida_analisi_tecnica/leFasiDelMercato'

  get 'guida_analisi_tecnica/ilTrend'

  get 'guida_analisi_tecnica/laTrendline'

  get 'guida_analisi_tecnica/inversioneDiTrend'

  get 'guida_analisi_tecnica/figureGrafiche'

  get 'guida_analisi_tecnica/testaESpalla'

  get 'guida_analisi_tecnica/doppioTriploMinimoMassimo'

  get 'guida_analisi_tecnica/spike'

  get 'guida_analisi_tecnica/triangoliFlagPennantRettangoli'

  get 'guida_analisi_tecnica/candeleGiapponesi'

  get 'guida_analisi_tecnica/standardELong'

  get 'guida_analisi_tecnica/marubozu'

  get 'guida_analisi_tecnica/harami'

  get 'guida_analisi_tecnica/doji'

  get 'guida_analisi_tecnica/configurazioniCandlestick'

  get 'guida_analisi_tecnica/bullishBearishEngulfing'

  get 'guida_analisi_tecnica/morningEveningStar'

  get 'guida_analisi_tecnica/hammerShootingStar'

  get 'guida_analisi_tecnica/hangingMan'

  get 'guida_analisi_tecnica/gap'

  get 'guida_analisi_tecnica/oscillatori'

  get 'guida_analisi_tecnica/rsi'

  get 'guida_analisi_tecnica/macd'

  get 'guida_analisi_tecnica/stocastico'

  get 'guida_analisi_tecnica/bandeDiBollinger'

  get 'guida_analisi_tecnica/indicatori'

  get 'guida_analisi_tecnica/medieMobili'

  get 'guida_analisi_tecnica/volumi'

  get 'guida_analisi_tecnica/ondeDiElliot'

  get 'guida_analisi_tecnica/ritracciamentiDiFibonacci'

    #mount Ckeditor::Engine => '/ckeditor'
    #root to: "posts#index"
  
    resources :posts
  end
  
  
  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'
   
  
  #FTSE MIB
  get 'analisi_tecnica_titolo/' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/index' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/a2a'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/atlantia'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/azimut_holding'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_generali'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_mediolanum'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banco_bpm'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/bper_banca'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/brembo'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/buzzi_unicem'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/campari'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/cnh_industrial'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/enel'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/eni'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/exor'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ferrari'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/fiat_chrysler_automobiles'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/finecobank'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/generali'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/intesa_sanpaolo'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/italgas'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/leonardo'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/luxottica'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/mediaset'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/mediobanca'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/moncler'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/poste_italiane'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/prysmian'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/recordati'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/saipem'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/salvatore_ferragamo'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/snam'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/stmicroelectronics'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/telecom_italia'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/tenaris'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/terna_rete_elettrica_nazionale'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ubi_banca'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/unicredit'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/unipol'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/unipolsai'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/yoox_net_a_porter_group'  => 'analisi_tecnica_titolo#index'
  
  
  #A
  get 'analisi_tecnica_titolo/acea'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/acotel_group'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/acsm_agam'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/aedes'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/aeffe'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/aeroporto_guglielmo_marconi'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/alerion_cleanpower'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ambienthesis'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/amplifon'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/anima_holding'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ansaldo_sts'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ascopiave'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/astaldi'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/astm'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/autogrill'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/autostrade_meridionali'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/avio'  => 'analisi_tecnica_titolo#index'
  
  
  #B
  get 'analisi_tecnica_titolo/bec_speakers' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_carige' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_farmafactoring' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_finnat' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_ifis' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_intermobiliare' => 'analisi_tecnica_titolo#index'

app/models/study.rb
class Study < ApplicationRecord
  belongs_to :stock
  belongs_to :user
  validates :resistance, numericality: {greater_than_or_equal_to: 0.00}, allow_blank: true
  validates :support, numericality: {greater_than_or_equal_to: 0.00}, allow_blank: true
  validates :direction, inclusion: { in: %w(None Uptrend Lateral Downtrend), message: "%{value} is not a valid direction value" }, allow_blank: true
  validates :mmp1, numericality: {greater_than_or_equal_to: 0.00}, allow_blank: true
  validates :mmp2, numericality: {greater_than_or_equal_to: 0.00}, allow_blank: true
  validates :gap, inclusion: { in: %w(None Up Down), message: "%{value} is not a valid gap value" }, allow_blank: true
  validates :trading_position, inclusion: { in: %w(None Long Neutral Short), message: "%{value} is not a valid trading position value" }, allow_blank: true
  validates :rsi, inclusion: { in: %w(None Overbought Neutral Oversold), message: "%{value} is not a valid RSI value" }, allow_blank: true
  validates :rsi_cross, inclusion: { in: %w(None Rising Falling), message: "%{value} is not a valid RSI crossover value" }, allow_blank: true
  validates :rsi_divergence , inclusion: { in: %w(None Bullish Neutral Bearish), message: "%{value} is not a valid RSI divergence value" }, allow_blank: true
  validates :stoch, inclusion: { in: %w(None Overbought Neutral Oversold), message: "%{value} is not a valid Stochastic value" }, allow_blank: true
  validates :stoch_cross, inclusion: { in: %w(None Rising Falling), message: "%{value} is not a valid Stochastic crossover value" }, allow_blank: true
  validates :stoch_divergence , inclusion: { in: %w(None Bullish Neutral Bearish), message: "%{value} is not a valid Stochastic divergence value" }, allow_blank: true
  validates :macd, inclusion: { in: %w(None Overbought Neutral Oversold), message: "%{value} is not a valid MACD value" }, allow_blank: true
  validates :macd_cross, inclusion: { in: %w(None Rising Falling), message: "%{value} is not a valid MACD crossover value" }, allow_blank: true
  validates :buy, numericality: {greater_than_or_equal_to: 0.00}, allow_blank: true
  validates :sell, numericality: {greater_than_or_equal_to: 0.00}, allow_blank: true
  validates :stop_loss, numericality: {greater_than_or_equal_to: 0.00}, allow_blank: true
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: [:show, :edit, :update, :destroy]
  before_action :require_user

  # GET /studies
  # GET /studies.json
  def index
    @studies = Study.all
    @user = User.find_by_email($user_email) 
  end

  # GET /studies/1
  # GET /studies/1.json
  def show
  end

  # GET /studies/new
  def new
    @study = Study.new
  end

  # GET /studies/1/edit
  def edit
  end

  # POST /studies
  # POST /studies.json
  def create
    @study = Study.new(study_params)

    respond_to do |format|
      if @study.save
        format.html { redirect_to @study, notice: 'Study was successfully created.' }
        format.json { render :show, status: :created, location: @study }
      else
        format.html { render :new }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studies/1
  # PATCH/PUT /studies/1.json
  def update
    respond_to do |format|
      if @study.update(study_params)
        format.html { redirect_to @study, notice: 'Study was successfully updated.' }
        format.json { render :show, status: :ok, location: @study }
      else
        format.html { render :edit }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1
  # DELETE /studies/1.json
  def destroy
    @study.destroy
    respond_to do |format|
      format.html { redirect_to studies_url, notice: 'Study was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study
      @study = Study.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def study_params
      params.require(:study).permit(:resistance, :support, :direction, :mmp1, :mmp2, :gap, :trading_position, :reversal_chart_pattern, :continuation_chart_pattern, :reversal_candlestick, :continuation_candlestick, :rsi, :rsi_cross, :rsi_divergence, :stoch, :stoch_cross, :stoch_divergence, :macd, :macd_cross, :buy, :sell, :stop_loss, :image_usrl, :note, :stock_id, :user_id)
    end
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/studies/_form.html.erb
<%= form_for(study) do |f| %>
  <% if study.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(study.errors.count, "error") %> prohibited this study from being saved:</h2>

      <ul>
      <% study.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :resistance %>
    <%= f.text_field :resistance %>
  </div>

  <div class="field">
    <%= f.label :support %>
    <%= f.text_field :support %>
  </div>

  <div class="field">
    <%= f.label :direction %>
    <%= f.text_field :direction %>
  </div>

  <div class="field">
    <%= f.label :mmp1 %>
    <%= f.text_field :mmp1 %>
  </div>

  <div class="field">
    <%= f.label :mmp2 %>
    <%= f.text_field :mmp2 %>
  </div>

  <div class="field">
    <%= f.label :gap %>
    <%= f.text_field :gap %>
  </div>

  <div class="field">
    <%= f.label :trading_position %>
    <%= f.text_field :trading_position %>
  </div>

  <div class="field">
    <%= f.label :reversal_chart_pattern %>
    <%= f.text_field :reversal_chart_pattern %>
  </div>

  <div class="field">
    <%= f.label :continuation_chart_pattern %>
    <%= f.text_field :continuation_chart_pattern %>
  </div>

  <div class="field">
    <%= f.label :reversal_candlestick %>
    <%= f.text_field :reversal_candlestick %>
  </div>

  <div class="field">
    <%= f.label :continuation_candlestick %>
    <%= f.text_field :continuation_candlestick %>
  </div>

  <div class="field">
    <%= f.label :rsi %>
    <%= f.text_field :rsi %>
  </div>

  <div class="field">
    <%= f.label :rsi_cross %>
    <%= f.text_field :rsi_cross %>
  </div>

  <div class="field">
    <%= f.label :rsi_divergence %>
    <%= f.text_field :rsi_divergence %>
  </div>

  <div class="field">
    <%= f.label :stoch %>
    <%= f.text_field :stoch %>
  </div>

  <div class="field">
    <%= f.label :stoch_cross %>
    <%= f.text_field :stoch_cross %>
  </div>

  <div class="field">
    <%= f.label :stoch_divergence %>
    <%= f.text_field :stoch_divergence %>
  </div>

  <div class="field">
    <%= f.label :macd %>
    <%= f.text_field :macd %>
  </div>

  <div class="field">
    <%= f.label :macd_cross %>
    <%= f.text_field :macd_cross %>
  </div>

  <div class="field">
    <%= f.label :buy %>
    <%= f.text_field :buy %>
  </div>

  <div class="field">
    <%= f.label :sell %>
    <%= f.text_field :sell %>
  </div>

  <div class="field">
    <%= f.label :stop_loss %>
    <%= f.text_field :stop_loss %>
  </div>

  <div class="field">
    <%= f.label :image_usrl %>
    <%= f.text_field :image_usrl %>
  </div>

  <div class="field">
    <%= f.label :note %>
    <%= f.text_area :note %>
  </div>

  <div class="field">
    <%= f.label :stock_id %>
    <%= f.text_field :stock_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/studies/edit.html.erb
<main id="main">
    <div id="content" class="container">
        <div class="row">
            <section id="primary" class="col-sm-12">
                <h1>Editing Study</h1>
                <%= render 'form', study: @study %>
                <%= link_to 'Show', @study %> |<%= link_to 'Back', studies_path %>
            </section>
        </div>
    </div>
</main>

app/views/studies/index.html.erb
<% meta_tag :robots, 'noindex, nofollow' %>

<main id="main">
    <div id="content" class="container">
        <div class="row">
            <div id="primary" class="col-sm-12">
                <p id="notice">
                    <%= notice %>
                </p>
                <h1>Studies</h1>
                <table class="tablesorter">
                    <thead>
                        <tr>
                            <th>
                                Resistance
                            </th>
                            <th>
                                Support
                            </th>
                            <th>
                                Direction
                            </th>
                            <th>
                                Mmp 1
                            </th>
                            <th>
                                Mmp 2
                            </th>
                            <th>
                                Gap
                            </th>
                            <th>
                                Trading Position
                            </th>
                            <th>
                                Reversal Chart Pattern
                            </th>
                            <th>
                                Continuation Chart Pattern
                            </th>
                            <th>
                                Reversal Candlestick
                            </th>
                            <th>
                                Continuation Candlestick
                            </th>
                            <th>
                                RSI
                            </th>
                            <th>
                                RSI Cross
                            </th>
                            <th>
                                RSI Divergence
                            </th>
                            <th>
                                Stochastic
                            </th>
                            <th>
                                Stochastic Cross
                            </th>
                            <th>
                                Stochastic Divergence
                            </th>
                            <th>
                                MACD
                            </th>
                            <th>
                                MACD Cross
                            </th>
                            <th>
                                B
                            </th>
                            <th>
                                Sell
                            </th>
                            <th>
                                Stoploss
                            </th>
                            <th>
                                Image url
                            </th>
                            <th>
                                Note
                            </th>
                            <th>
                                Stock
                            </th>
                            <th>
                                User
                            </th>
                            <th colspan="3">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @studies.each do |study| %>
                        <tr class="<%= cycle('even', 'odd') -%>">
                            <td>
                                <%= study.resistance %>
                            </td>
                            <td>
                                <%= study.support %>
                            </td>
                            <td>
                                <%= study.direction %>
                            </td>
                            <td>
                                <%= study.mmp1 %>
                            </td>
                            <td>
                                <%= study.mmp2 %>
                            </td>
                            <td>
                                <%= study.gap %>
                            </td>
                            <td>
                                <%= study.trading_position %>
                            </td>
                            <td>
                                <%= study.reversal_chart_pattern %>
                            </td>
                            <td>
                                <%= study.continuation_chart_pattern %>
                            </td>
                            <td>
                                <%= study.reversal_candlestick %>
                            </td>
                            <td>
                                <%= study.continuation_candlestick %>
                            </td>
                            <td>
                                <%= study.rsi %>
                            </td>
                            <td>
                                <%= study.rsi_cross %>
                            </td>
                            <td>
                                <%= study.rsi_divergence %>
                            </td>
                            <td>
                                <%= study.stoch %>
                            </td>
                            <td>
                                <%= study.stoch_cross %>
                            </td>
                            <td>
                                <%= study.stoch_divergence %>
                            </td>
                            <td>
                                <%= study.macd %>
                            </td>
                            <td>
                                <%= study.macd_cross %>
                            </td>
                            <td>
                                <%= study.buy %>
                            </td>
                            <td>
                                <%= study.sell %>
                            </td>
                            <td>
                                <%= study.stop_loss %>
                            </td>
                            <td>
                                <%= study.image_usrl %>
                            </td>
                            <td>
                                <%= study.note %>
                            </td>
                            <td>
                                <%= study.stock %>
                            </td>
                            <td>
                                <%= study.user %>
                            </td>
                            <td>
                                <%= link_to 'Show', study %>
                            </td>
                            <td>
                                <%= link_to 'Edit', edit_study_path(study) %>
                            </td>
                            <td>
                                <%= link_to 'Destroy', study, method: :delete, data: { confirm: 'Are you sure?' } %>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
                <br>
                <%= link_to 'New Study', new_study_path %>
            </div>
        </div>
    </div>
</main>

app/views/studies/new.html.erb
<h1>New Study</h1>

<%= render 'form', study: @study %>

<%= link_to 'Back', studies_path %>

app/views/studies/show.html.erb
<main id="main">
    <div id="content" class="container">
        <div class="row">
            <section id="primary" class="col-sm-12">
                <p id="notice">
                    <%= notice %>
                </p>
                <p>
                    <strong>Resistance:</strong>
                    <%= @study.resistance %>
                </p>
                <p>
                    <strong>Support:</strong>
                    <%= @study.support %>
                </p>
                <p>
                    <strong>Direction:</strong>
                    <%= @study.direction %>
                </p>
                <p>
                    <strong>Mmp1:</strong>
                    <%= @study.mmp1 %>
                </p>
                <p>
                    <strong>Mmp2:</strong>
                    <%= @study.mmp2 %>
                </p>
                <p>
                    <strong>Gap:</strong>
                    <%= @study.gap %>
                </p>
                <p>
                    <strong>Tradingposition:</strong>
                    <%= @study.trading_position %>
                </p>
                <p>
                    <strong>Reversalchartpattern:</strong>
                    <%= @study.reversal_chart_pattern %>
                </p>
                <p>
                    <strong>Continuationchartpattern:</strong>
                    <%= @study.continuation_chart_pattern %>
                </p>
                <p>
                    <strong>Reversalcandlestick:</strong>
                    <%= @study.reversal_candlestick %>
                </p>
                <p>
                    <strong>Continuationcandlestick:</strong>
                    <%= @study.continuation_candlestick %>
                </p>
                <p>
                    <strong>Rsi:</strong>
                    <%= @study.rsi %>
                </p>
                <p>
                    <strong>Rsicross:</strong>
                    <%= @study.rsi_cross %>
                </p>
                <p>
                    <strong>Rsidivergence:</strong>
                    <%= @study.rsi_divergence %>
                </p>
                <p>
                    <strong>Stoch:</strong>
                    <%= @study.stoch %>
                </p>
                <p>
                    <strong>Stochcross:</strong>
                    <%= @study.stoch_cross %>
                </p>
                <p>
                    <strong>Stochdivergence:</strong>
                    <%= @study.stoch_divergence %>
                </p>
                <p>
                    <strong>Macd:</strong>
                    <%= @study.macd %>
                </p>
                <p>
                    <strong>Macdcross:</strong>
                    <%= @study.macd_cross %>
                </p>
                <p>
                    <strong>Buy:</strong>
                    <%= @study.buy %>
                </p>
                <p>
                    <strong>Sell:</strong>
                    <%= @study.sell %>
                </p>
                <p>
                    <strong>Stoploss:</strong>
                    <%= @study.stop_loss %>
                </p>
                <p>
                    <strong>Imageurl:</strong>
                    <%= @study.image_usrl %>
                </p>
                <p>
                    <strong>Note:</strong>
                    <%= @study.note %>
                </p>
                <p>
                    <strong>Stock:</strong>
                    <%= @study.stock %>
                </p>
                <p>
                    <strong>User:</strong>
                    <%= @study.user %>
                </p>
                <%= link_to 'Edit', edit_study_path(@study) %> |<%= link_to 'Back', studies_path %>
            </section>
        </div>
    </div>
</main>