config/routes.rb
Rails.application.routes.draw do
  get 'guida_analisi_tecnica/index'

  get 'guida_analisi_tecnica/leFasiDelMercato'

  get 'guida_analisi_tecnica/ilTrend'

  get 'guida_analisi_tecnica/laTrendline'

  get 'guida_analisi_tecnica/inversioneDiTrend'

  get 'guida_analisi_tecnica/figureGrafiche'

  get 'guida_analisi_tecnica/testaESpalla'

  get 'guida_analisi_tecnica/doppioTriploMinimoMassimo'

  get 'guida_analisi_tecnica/spike'

  get 'guida_analisi_tecnica/triangoliFlagPennantRettangoli'

  get 'guida_analisi_tecnica/candeleGiapponesi'

  get 'guida_analisi_tecnica/standardELong'

  get 'guida_analisi_tecnica/marubozu'

  get 'guida_analisi_tecnica/harami'

  get 'guida_analisi_tecnica/doji'

  get 'guida_analisi_tecnica/configurazioniCandlestick'

  get 'guida_analisi_tecnica/bullishBearishEngulfing'

  get 'guida_analisi_tecnica/morningEveningStar'

  get 'guida_analisi_tecnica/hammerShootingStar'

  get 'guida_analisi_tecnica/hangingMan'

  get 'guida_analisi_tecnica/gap'

  get 'guida_analisi_tecnica/oscillatori'

  get 'guida_analisi_tecnica/rsi'

  get 'guida_analisi_tecnica/macd'

  get 'guida_analisi_tecnica/stocastico'

  get 'guida_analisi_tecnica/bandeDiBollinger'
  #get 'xyz' => 'guida_analisi_tecnica#bandeDiBollinger'

  get 'guida_analisi_tecnica/indicatori'

  get 'guida_analisi_tecnica/medieMobili'

  get 'guida_analisi_tecnica/volumi'

  get 'guida_analisi_tecnica/ondeDiElliot'

  get 'guida_analisi_tecnica/ritracciamentiDiFibonacci'

  mount Ckeditor::Engine => '/ckeditor'
  get 'chi_siamo/index'
  get 'chi_siamo/' => 'chi_siamo#index'

  get 'contatti/index'
  get 'contatti/' => 'contatti#index'

  get 'sources/source1'

  get 'sources/source2'

  get 'sources/source3'

  get 'sources/source4'

  get 'sources/source5'

  get 'sources/source6'

  get 'trading_plan/index'

  get 'filters/filter_overAllResistancesStocks'
  get 'filters/filter_belowAllSupportsStocks'
  
  get 'filters/filter_overResistanceBorsaItaliana'
  get 'filters/filter_belowSupportBorsaItaliana'
  
  get 'filters/filter_overResistanceSoleXXIVOre'
  get 'filters/filter_belowSupportSoleXXIVOre'
  
  get 'filters/filter_overResistanceRepubblica'
  get 'filters/filter_belowSupportRepubblica'

  get 'filters/filter_suggestionsSoleXXIVOre'
  get 'filters/filter_suggestionsInvestingDotCom'
  get 'filters/filter_suggestionsMilanoFinanza'

  get 'filters/filter_overResistanceStocksOnStudy'
  get 'filters/filter_belowSupportStocksOnStudy'

  
  get 'filters/filter_trendReinforcement'
  get 'filters/filter_trendChanging'
  
  
  get 'study_page/index'
  get 'study_page/' => 'study_page#index'
  post 'study_page/index'  => 'study_page#create' 

  get 'stock_page/index'
  get 'stock_page/' => 'stock_page#index'
  

  resources :markets
  resources :studies
  resources :analyses
  resources :stocks
  resources :urls
  
  get 'welcome/index'
  get 'welcome/' => 'welcome#index'

  root 'welcome#index'

  get 'signup'  => 'users#new' 
  resources :users

  get 'login'  => 'sessions#new' 

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
  
  Rails.application.routes.draw do
  get 'guida_analisi_tecnica/index'

  get 'guida_analisi_tecnica/leFasiDelMercato'

  get 'guida_analisi_tecnica/ilTrend'

  get 'guida_analisi_tecnica/laTrendline'

  get 'guida_analisi_tecnica/inversioneDiTrend'

  get 'guida_analisi_tecnica/figureGrafiche'

  get 'guida_analisi_tecnica/testaESpalla'

  get 'guida_analisi_tecnica/doppioTriploMinimoMassimo'

  get 'guida_analisi_tecnica/spike'

  get 'guida_analisi_tecnica/triangoliFlagPennantRettangoli'

  get 'guida_analisi_tecnica/candeleGiapponesi'

  get 'guida_analisi_tecnica/standardELong'

  get 'guida_analisi_tecnica/marubozu'

  get 'guida_analisi_tecnica/harami'

  get 'guida_analisi_tecnica/doji'

  get 'guida_analisi_tecnica/configurazioniCandlestick'

  get 'guida_analisi_tecnica/bullishBearishEngulfing'

  get 'guida_analisi_tecnica/morningEveningStar'

  get 'guida_analisi_tecnica/hammerShootingStar'

  get 'guida_analisi_tecnica/hangingMan'

  get 'guida_analisi_tecnica/gap'

  get 'guida_analisi_tecnica/oscillatori'

  get 'guida_analisi_tecnica/rsi'

  get 'guida_analisi_tecnica/macd'

  get 'guida_analisi_tecnica/stocastico'

  get 'guida_analisi_tecnica/bandeDiBollinger'

  get 'guida_analisi_tecnica/indicatori'

  get 'guida_analisi_tecnica/medieMobili'

  get 'guida_analisi_tecnica/volumi'

  get 'guida_analisi_tecnica/ondeDiElliot'

  get 'guida_analisi_tecnica/ritracciamentiDiFibonacci'

    #mount Ckeditor::Engine => '/ckeditor'
    #root to: "posts#index"
  
    resources :posts
  end
  
  
  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'
   
  
  #FTSE MIB
  get 'analisi_tecnica_titolo/' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/index' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/a2a'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/atlantia'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/azimut_holding'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_generali'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_mediolanum'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banco_bpm'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/bper_banca'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/brembo'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/buzzi_unicem'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/campari'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/cnh_industrial'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/enel'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/eni'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/exor'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ferrari'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/fiat_chrysler_automobiles'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/finecobank'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/generali'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/intesa_sanpaolo'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/italgas'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/leonardo'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/luxottica'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/mediaset'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/mediobanca'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/moncler'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/poste_italiane'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/prysmian'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/recordati'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/saipem'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/salvatore_ferragamo'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/snam'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/stmicroelectronics'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/telecom_italia'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/tenaris'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/terna_rete_elettrica_nazionale'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ubi_banca'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/unicredit'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/unipol'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/unipolsai'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/yoox_net_a_porter_group'  => 'analisi_tecnica_titolo#index'
  
  
  #A
  get 'analisi_tecnica_titolo/acea'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/acotel_group'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/acsm_agam'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/aedes'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/aeffe'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/aeroporto_guglielmo_marconi'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/alerion_cleanpower'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ambienthesis'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/amplifon'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/anima_holding'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ansaldo_sts'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/ascopiave'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/astaldi'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/astm'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/autogrill'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/autostrade_meridionali'  => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/avio'  => 'analisi_tecnica_titolo#index'
  
  
  #B
  get 'analisi_tecnica_titolo/bec_speakers' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_carige' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_farmafactoring' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_finnat' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_ifis' => 'analisi_tecnica_titolo#index'
  get 'analisi_tecnica_titolo/banca_intermobiliare' => 'analisi_tecnica_titolo#index'

app/models/market.rb
class Market < ApplicationRecord
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :set_market, only: [:show, :edit, :update, :destroy]
  before_action :require_user

  # GET /markets
  # GET /markets.json
  def index
    @markets = Market.all
    @user = User.find_by_email($user_email) 
  end

  # GET /markets/1
  # GET /markets/1.json
  def show
  end

  # GET /markets/new
  def new
    @market = Market.new
  end

  # GET /markets/1/edit
  def edit
  end

  # POST /markets
  # POST /markets.json
  def create
    @market = Market.new(market_params)

    respond_to do |format|
      if @market.save
        format.html { redirect_to @market, notice: 'Market was successfully created.' }
        format.json { render :show, status: :created, location: @market }
      else
        format.html { render :new }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markets/1
  # PATCH/PUT /markets/1.json
  def update
    respond_to do |format|
      if @market.update(market_params)
        format.html { redirect_to @market, notice: 'Market was successfully updated.' }
        format.json { render :show, status: :ok, location: @market }
      else
        format.html { render :edit }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markets/1
  # DELETE /markets/1.json
  def destroy
    @market.destroy
    respond_to do |format|
      format.html { redirect_to markets_url, notice: 'Market was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_market
      @market = Market.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def market_params
      params.require(:market).permit(:name, :value, :variation)
    end
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/_form.html.erb
<%= form_for(market) do |f| %>
  <% if market.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(market.errors.count, "error") %> prohibited this market from being saved:</h2>

      <ul>
      <% market.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :value %>
    <%= f.text_field :value %>
  </div>

  <div class="field">
    <%= f.label :variation %>
    <%= f.text_field :variation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/markets/edit.html.erb
<main id="main">
    <div id="content" class="container">
        <div class="row">
            <section id="primary" class="col-sm-12">
                <h1>Editing Market</h1>
                <%= render 'form', market: @market %>
                <%= link_to 'Show', @market %> |<%= link_to 'Back', markets_path %>
            </section>
        </div>
    </div>
</main>

app/views/markets/index.html.erb
<% meta_tag :robots, 'noindex, nofollow' %>

<main id="main">
    <div id="content" class="container">
        <div class="row">
            <div id="primary" class="col-sm-12">
                <p id="notice">
                    <%= notice %>
                </p>
                <h1>Markets</h1>
                <table class="tablesorter">
                    <thead>
                        <tr>
                            <th>
                                Name
                            </th>
                            <th>
                                Value
                            </th>
                            <th>
                                Variation
                            </th>
                            <th colspan="3">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @markets.each do |market| %>
                        <tr class="<%= cycle('even', 'odd') -%>">
                            <td title="market.name">
                                <%= market.name %>
                            </td>
                            <td title="market.value">
                                <%= market.value %>
                            </td>
                            <td title="market.variation">
                                <%= market.variation %>
                            </td>
                            <td>
                                <%= link_to 'Show', market %>
                            </td>
                            <td>
                                <%= link_to 'Edit', edit_market_path(market) %>
                            </td>
                            <td>
                                <%= link_to 'Destroy', market, method: :delete, data: { confirm: 'Are you sure?' } %>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
                <br>
                <%= link_to 'New Market', new_market_path %>
            </div>
        </div>
    </div>
</main>

app/views/markets/new.html.erb
<h1>New Market</h1>

<%= render 'form', market: @market %>

<%= link_to 'Back', markets_path %>

app/views/markets/show.html.erb
<main id="main">
    <div id="content" class="container">
        <div class="row">
            <section id="primary" class="col-sm-12">
                <p id="notice">
                    <%= notice %>
                </p>
                <p>
                    <strong>Name:</strong>
                    <%= @market.name %>
                </p>
                <p>
                    <strong>Value:</strong>
                    <%= @market.value %>
                </p>
                <p>
                    <strong>Variation:</strong>
                    <%= @market.variation %>
                </p>
                <%= link_to 'Edit', edit_market_path(@market) %> |<%= link_to 'Back', markets_path %>
            </section>
        </div>
    </div>
</main>